### ISSUE TITLE
insane instability on raspberry pi 3b+

### ISSUE THREAD

**Issue by ghost** [aqualung99/dosbox-0.74-ES#2]
I compiled this dosbox to try a gles option and scale my games but omf 2097 not even pass the setup screen to the game and the cpu usage goes to 100% all the time. no crash, no nothing.. only a "_" on the left upper corner.

**Comment by aqualung99** [comment]
I haven't tested the Pi 3b since I don't own one, so I'm not sure what might be the problem.
Couple of obvious things to test though: first, are you sure the Pi 3b+ supports OpenGL-ES, including version 1.00 pixel shaders and vertex shaders? Do you have another OpenGL-ES application you can test with to confirm this?
Second, are you sure the version of SDL 2.0 that you are using supports your hardware? Usually, you would also have to rebuild SDL 2.0 yourself from the sources. When doing so, SDL 2.0 itself will notify you which features it can support (including whether it can support OpenGL-ES or not) on your hardware.
I was just playing OMF using my port two days ago, so it definitely works!! But Linux hardware configurations can vary more widely than Windows ones, so tracking down the individual issues that happen on each platform can be tricky.
Again, if you are really interesting in getting my version working on the Pi, we need to confirm two things:
  1> Your Pi supports OpenGL-ES including pixel shader version 1.00
  2> Your current version of the SDL 2.0 library supports the Pi 3b and will let applications utilize the OpenGL-ES features.

Do you have any other OpenGL applications working on your Pi? How about any SDL 2.0 applications that are working? My version of DosBox relies on SDL 2.0 to provide the "middle-man" interface between my program and the actual hardware. If SDL 2.0 is working 100% for you, most likely my DosBox will as well!

**Comment by ghost** [comment]
Yes, mi pi3b+ has at least gles 1.5 and even optional but experimental
opengl mesa drivers. I used another dosbox build with gles made for odroid.
works greater than the repo dosbox, but only could scale on mesa drivers...
and far worst performance than the legacy driver. dont know why on legacy
driver cant scale my games... but it works. xrandr does't work on legacy
drivers, but in this case I only ask to scale the game, not to change the
resolution. I compiled sdl2 and  fluidsynth to build your dosbox. without
fluidsynth the build process crash, dont matter if I set to disable midi.
and dont know why with your build the cpu goes automatically at 100% even
if not game its loaded, because i haven't seen any dosbox than uses more
than one core.

this its the log when I start your dosbox on terminal...


DOSBox version 0.74-ES
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file
/home/pi/.dosbox/dosbox-0.74-ES.conf
OpenGL-ES
Vendor: VMware, Inc.
Renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
Version: 3.0 Mesa 13.0.6
Shader Version: 1.30
Compiled shader "/usr/local/share/dosbox/logo.vs"
Compiled shader "/usr/local/share/dosbox/logo.ps"
Shaders linked successfully. Attributes found:
position
Uniforms found:
texUnit
fadeFactor

Compiled shader "/usr/local/share/dosbox/DosBoxMain.vs"
Compiled shader "/usr/local/share/dosbox/DosBoxMain.ps"
Compiled shader "/usr/local/share/dosbox/DosBoxNoPal.ps"
Shaders linked successfully. Attributes found:
position
Uniforms found:
aspectFix
texUnit
palUnit
one
uvRatio

Shaders linked successfully. Attributes found:
position
Uniforms found:
aspectFix
texUnit
one
uvRatio

Compiled shader "/usr/local/share/dosbox/fb.vs"
Compiled shader "/usr/local/share/dosbox/fb.ps"
Shaders linked successfully. Attributes found:
position
Uniforms found:
aspectFix
texcoordScale
texUnit

Audio device 0: bcm2835 ALSA, bcm2835 ALSA
Audio device 1: bcm2835 ALSA, bcm2835 IEC958/HDMI
FluidSynth: Synthesizer running at a sample rate of 41000
MIDI:Opened device:fluidsynth

**Comment by ghost** [comment]
I tried both drivers with your dosbox...legacy and mesa...same results.

**Comment by aqualung99** [comment]
Your startup log certainly looks like everything is working correctly!

  Next thing I would recommend, would be to edit your "DosBox-0.74-ES.conf" file. Look for the line that reads "cycles=auto" and change it to read "cycles=500".  That *might* fix the problem where the CPU gets pegged to 100% (although will be a very slow emulation speed....its just a temporary test.)

  I'm not sure if that will fix the video output though. Again, your log file looks like the video part is operating 100% correctly. It's possible I may have to buy a Pi 3b in order to test your configuration. Another possibility would be to make a special build for you that would write some additional log info to help try to track down the issue.

  Now, the log entries about the Audio devices only happen *after* the DosBox logo has already appeared and then faded-out. Do you see the DosBox logo in orange? Does it fade-out correctly? Or, does that window even open at all?




________________________________

**Comment by ghost** [comment]
Even at 500 cycles... my cpu did a weird  sound with you dosbox dude
hahahahaha

**Comment by aqualung99** [comment]
Bummer! 😞

  Again, you will need to decide how important it is to you to get this working. If it's not that important, then no need to sweat it -- I'll keep in mind that the Pi 3b+ doesn't work right now and is something I should look at when I have the time.

  If it's really important to you to get this working, I'll probably need lots of help from you in order to make that happen. I'm willing to spend some time to try to get this fixed though, if you are.

________________________________

**Comment by ghost** [comment]
Yes. Tomorrow i will deal with your dobox again. I need to rewrite my sd
now because of other things. Its really important to me if i could scale
the game on legacy drivers and it performe at least like the odroid build
posted by maveric... it runs amazing on legacy but didnt scale the game..
dont know if its something with the raspberry pi driver or not...

**Comment by ghost** [comment]
Could be fluidsynth ?? Dont know why but i hate him
.. it take me 2 hour to install to pass your dosbox build.

**Comment by aqualung99** [comment]
Yeah, no problem. I only ever tested Linux on two different platforms: Odroid 3 and PC. It's probably not an error with the drivers themselves -- more likely just my program making some assumptions that don't apply to the Pi.
The most immediate info that will be useful would be whether or not the DosBox Logo window even opens for you at all. It sounds to me like it does open, but that nothing ever displays inside it. So, you get a blank window and 100% CPU usage. But no logo and no other display at all.
  If that's accurate, it is most likely a problem with trying to set the display properties of the window. Let me think a little bit about how to best track down the root source of the error -- I may have another experimental version for you to try in the future.

**Comment by ghost** [comment]
No. Dosbox opened on an extremly tiny window. And I am able to load omf...
cant pass the setup... les than 1 fps... 100% cpu!!

**Comment by aqualung99** [comment]
Oh! Ok, I think I see.
Keep in mind, the ODroid was *barely* able to output at 640x400....
The memory bus on these SoC chips is shared between the video and the CPU. It is the memory bus that is killing your CPU performance.
If it's working, but the performance is bad, there is nothing I can do to remedy that. My code does almost nothing -- I receive a VGA scanline from the DosBox video subsystem,  and I update the OpenGL texture accordingly.  This needs to happen at least 200 times per frame.
I'm going to go ahead and order a Pi 3b and see if low performance on the hardware side is indeed the only problem.

________________________________

**Comment by ghost** [comment]
Thanks. I am thinking to upgrade my pi with another more capable arm
board...

**Comment by aqualung99** [comment]
I'll investigate the capabilities of the Pi 3 soon.
In the meantime, here are some other things to try:

> Make sure X11 is running at 640x480 or lower.
> Set DosBox window size to 320x200 or smaller
> Set frameskip=1 or maybe frameskip=2


Any of those should increase your performance-- maybe you'll find a combination that works.
________________________________

**Comment by ghost** [comment]
Thatks dude. But I get a great performance on an odroid gles build.
